spring:
  application:
    name: ordering-system
  main:
    allow-bean-definition-overriding: true
  mongodb:
    uri: mongodb://localhost:27017/bmg_ordering

logging:
  level:
    root: INFO
    com.banhmygac: DEBUG